#!/bin/sh

export PATH=/bin:/sbin:/usr/bin:/usr/sbin

export BRIDGE_IFACE=br0
export WIFI_IFACE=ra0
export VLAN_IFACE=eth2
export USB_IFACE=ra1
export CLI_IFACE=apcli0
export NAT_IFACE=$BRIDGE_IFACE

export RESOLV=/etc/resolv.conf
export HOSTS=/etc/hosts
export TZ_DATA=/etc/TZ
export SERVICES=/etc/services
export MOTD=/etc/motd
export CRON_DIR="/etc/crontabs"
export IGMPPROXY_CONF="/etc/igmpproxy.conf"
export UPNP_CONF="/etc/upnp.conf"
export IGNORE_ERR=0 # if 1, boot try to continue anyway
export BOOT_NOW=0 # Write boot log to /dev/kmsg

export SYS_USER="admin"
export SYS_PASS="admin"

export UDPXY=udpxy
export DHCPD=dnsmasq
export DHCPD_IFACE=$WIFI_IFACE
export DHCPD_CONF_FILE="/etc/dnsmasq.conf"
export DHCPD_DOMAIN="Triolan"
export DHCPD_LOG="/tmp/dnsmasq.log"
export DHCPD_RANGE_BEGIN="192.168.182.2"
export DHCPD_RANGE_END="192.168.182.250"
export DHCPD_GATEWAY="192.168.182.1"
export DHCPD_LEASE_TIME=86400

## SSH

export SSHD=dropbear
export SSHD_KEY_GEN=dropbearkey
export SSHD_RSA_KEY="/etc/dropbear/dropbear_rsa_host_key"
export SSHD_DSS_KEY="/etc/dropbear/dropbear_dss_host_key"


## Default params

export DEFAULT_NAT_ENABLE=1
export DEFAULT_HWNAT_ENABLE=1
export DEFAULT_DHCPD_ENABLED=1
export DEFAULT_BRIDGE_ENABLED=1
export DEFAULT_UDPXY_ENABLED=0
export DEFAULT_IGMPPROXY_ENABLED=1
export DEFAULT_UDPXY_PORT=80
export DEFAULT_INIT_ENABLE=1
export DEFAULT_TUNE_NET_ENABLED=1
export DEFAULT_AUTH_ENABLE=0 # build-in
export DEFAULT_WIFI_SSID_AP="Alta"
export DEFAULT_WIFI_CHANNEL=7 # auto
export DEFAULT_WIFI_MODE=9 # B/G/N
export DEFAULT_WIFI_WORK_MODE=ap
export DEFAULT_CONN_MODE=DHCP
export DEFAILT_HOSTNAME_MODE=0 # auto
export DEFAULT_DNS_1="8.8.4.4"
export DEFAULT_DNS_2="8.8.8.8"
export DEFAULT_NTP="time.in.ua"
export DEFAULT_UPNP_ENABLED=1
export DEFAULT_STREAM_ENABLED=0
export DEFAULT_IDS_ENABLED=0


export VENDOR_F_BYTE=0x66
export VENDOR_S_BYTE=0x99

export DEFAULT_STRICT_WIFI=0

# Update system

export DEFAULT_UPDATE_SERVER_ADDR="80.73.15.84"
export DEFAULT_UPDATE_SERVER_PORT=9966
export DEFAULT_UPDATE_FILE_NAME="update.tar.lzma"
export DEFAULT_UPDATE_VERSION_FILE="version.bin"
export DEFAULT_UPDATE_ROOTFS_PART="Kernel"
export DEFAULT_UPDATE_BOOTLOADER_PART="Bootloader"

export GPIO_PIN_LED=11

# MJPG

export DEFAULT_MJPG_RSN="320x240"
export DEFAULT_MJPG_FPS=10
export DEFAULT_MJPG_PORT=9999
export DEFAULT_MJPG_DEVICE="/dev/video0"
