obj-$(CONFIG_DTB_RT2880_EVAL) := rt2880_eval.dtb.o
obj-$(CONFIG_DTB_RT305X_EVAL) := rt3052_eval.dtb.o
obj-$(CONFIG_DTB_RT3883_EVAL) := rt3883_eval.dtb.o
obj-$(CONFIG_DTB_MT7620_EVAL) := mt7620_eval.dtb.o
obj-$(CONFIG_DTB_RT5350_EVAL) := rt5350_eval.dtb.o
